### ISSUE TITLE
Add --explchecks switch in build model tab

### ISSUE THREAD

**Issue by tquatmann** [DGBTechnologies/StormGUI#10]
Similar to issue #7, I suggest to add the switch `--explchecks` when building the model. This performs a few more sanity checks during model building, detecting potential modeling errors. Of course, this slightly increases the runtime but I think that is negligible in this case.

**Comment by tquatmann** [comment]
I realized that there was an issue within storm with these checks for assignments to transient variables.
I just [pushed a fix to storm](https://github.com/moves-rwth/storm/commit/8b68fbf94812341af4918e578cdbe84695ee0c7b), but if you are running the GUI with a Storm version that is older than *today* it is probably not the best idea to enforce the `--explchecks` switch.

**Comment by AhmadZafarDGB** [comment]
Added --explchecks switch.
