### ISSUE TITLE
empty action labels on edges

### ISSUE THREAD

**Issue by tquatmann** [DGBTechnologies/StormGUI#4]
[Apologies if this is already fixed in the recent release]

I noticed that when we add an edge in the automaton editor and leave the text field for the action label blank, it will create the entry `"action": ""` for the edge in the JANI code which is not valid Jani as the empty word is not a valid identifier.

I would have expected that the `"action"` entry is omitted as a whole, if it's text field is empty.

**Comment by AhmadZafarDGB** [comment]
Fixed in the new release.
