### ISSUE TITLE
Property R{...}max=? [LRA] parsed as Smin

### ISSUE THREAD

**Issue by tquatmann** [DGBTechnologies/StormGUI#5]
In the file [sendreceiver.jgm.txt](https://github.com/DGBTechnologies/StormGUI/files/5830988/sendreceiver.jgm.txt) (renamed because of github reasons...) I noticed that the property `R{"p"}max=? [LRA]` is translated to JANI using the `Smin` operator instead of `Smax`.

**Comment by tquatmann** [comment]
In a similar direction, `P<1 [ F "goal" ]` apparently is parsed as `Pmin<1 [ F "goal"]` but should be `Pmax<1 [F "goal"]`.

Note that here, min or max depends on whether we have a lower bound (`>`, `>=`) or upper bound (`<`, `<=`), i.e. `P>=1 [ F "goal"]` should indeed be `Pmin>=1 [ F "goal"]`. `P=?  ...` results in an error for nondeterministic models. Same for reward-based properties (at least this is how PRISM and Storm interprete these formulas).

**Comment by AhmadZafarDGB** [comment]
Fixed both things
