### ISSUE TITLE
Problems with Reward/Label definitions

### ISSUE THREAD

**Issue by tquatmann** [DGBTechnologies/StormGUI#6]
I noticed that for translating (global) rewards and label definition to JANI, a new automaton `ForGlobalLabelsAndRewards` is introduced where auxiliary transient variables are set. I see two potential problems with this approach:

Firstly, the current implementation ignores transition rewards on non-synchronizing edges (i.e. edges without an edge label).

Secondly (and this is more of a usability concern), it might not be obvious to the user when exactly the defining expressions are evaluated.
For example, in [sendreceiver.jgm.txt](https://github.com/DGBTechnologies/StormGUI/files/5831050/sendreceiver.jgm.txt) I wanted to have rewards `penality` which should essentially equal the value of transient variable `p`. However, there are location vectors where we set `p:=1 & penalty:=p`. Note that when assigning `penalty:=p`, `p` does not have value `1` yet. A similar thing happens for edge-destination assignments where some variables (actually also non-transient ones) might not be set yet.

**Comment by tquatmann** [comment]
I just noticed that the jani-spec actually disallows transient variables to occur on the right-hand-side of transient-value assignments at locations. Hence, when defining labels and state-based rewards we shall not use transient variables.

**Comment by AhmadZafarDGB** [comment]
Issue with the last approach. Now remove local labels and rewards.  In properties, if anyone is using labels or rewards, will replace with expression.
